### ISSUE TITLE
module import failing on react app

### ISSUE THREAD

**Issue by kinshukJ** [tamasszoke/neat-rtc#17]
Hi, thanks sharing a pretty neat framework! I'm working with a react app, and upon importing the module using `import NeatRTC from 'neatRTC'`, I get module not found. I see that neatRTC shows up under node mudules folder. However, it is missing the dist folder. I'm fairly new to react, but I think the package not having a dist folder might be the issue

**Comment by tamasszoke** [comment]
Hi kinshukJ, thank you for bringing this to my attention.
I have checked the issue and solved it in the 1.0.10 version.

**Comment by tamasszoke** [comment]
Hi kinshukJ, thank you for bringing this to my attention.
I have checked the issue and solved it in the 1.0.10 version.

You can use it as `import NeatRTC from 'neat-rtc'`.
