### ISSUE TITLE
[enhancement] Provide own MediaStream

### ISSUE THREAD

**Issue by jamiegluk** [tamasszoke/neat-rtc#27]
I'd like to provide my own `MediaStream` to `rtc.media("start")`.

Neat-RTC currently hardcodes `getUserMedia` and provides no access to the internal `streamLocal`, so the only way of doing this from my own code, as it stands, is to temporarily override `navigator.getUserMedia` and inject my own stream into the success callback. This is not good, so I'd like to provide a stream as an optional parameter.

I am using this to switch between webcam and screen-sharing (`getDisplayMedia`), whilst controlling the audio stream.

I can submit a pull request if you wish?

**Comment by tamasszoke** [comment]
Hi, I'm busy currently, but I'll look into this next week.

**Comment by tamasszoke** [comment]
I'll do a complete rewrite, possibly in a couple of weeks, including this feature.
