### ISSUE TITLE
STUN/TURN?

### ISSUE THREAD

**Issue by rush86999** [tamasszoke/neat-rtc#3]
to use something like this in production, how would you implement a stun/turn server with this? Is there any guidelines or tutorial on this? I might be asking the wrong question as i haven't looked at your codebase and I m new to WebRTC in general

**Comment by tamasszoke** [comment]
It uses the default STUN server from Google, but you can use your own STUN/TURN server. I added the feature to configure the RTCPeerConnection, check the config section of the readme.
