### ISSUE TITLE
Connect to another frontend

### ISSUE THREAD

**Issue by isaac1104** [tamasszoke/neat-rtc#4]
Hello,

I am playing around with the react example and was wondering if it would be possible to connect the example to another front-end application (eg. vanilla react) that does not use neat-rtc library. Will it be able to send/receive media like how it is doing in the example?

![Untitled Diagram](https://user-images.githubusercontent.com/28583016/68842298-7d821a80-0709-11ea-9a2b-0fee28c02616.png)

Sorry if I'm not making any sense. Kinda hard to explain.... Please let me know if you need further explanations

Thank you

UPDATE

I installed socket.io-client on react without  neat-rtc and i was able to connect to the server from the example. I am also able to join the room and get signaling messages using the socket.on(‘join’) and socket.on(‘signaling’) event. But I’m still not sure how to stream webcam from one app to the other

**Comment by tamasszoke** [comment]
Without Neat-RTC you have to write your own [WebRTC](https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API) code to create the peerconnection,  add/remove streams and datachannels. Neat-RTC is meant to use it on both ends.

My suggestion is to use both applications in the same way, mixing is not an easy option.

Howewer, if you want to try it, you have to adjust the other application's WebRTC code to the Neat-RTC names/methods. A couple of things to adjust on the application without Neat-RTC:

1. The whole signaling process (offer/answer/candidates).
2. Media channel methods (start/stop/stopremote).
3. Data channel methods (send/receive).

Check the [source code](https://github.com/tamasszoke/neat-rtc/blob/master/src/index.js) if you need further clarification.

**Comment by isaac1104** [comment]
Thank you for your reply. I just ended up using neat-rtc because like you said, mixing wasn't an easy option. I'll close this since I know that mixing is possible.
